version: '3.8'
services:
  app:
    build: .
    container_name: prediksi_cuaca_app
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - appnet

  web:
    image: nginx:stable
    container_name: prediksi_cuaca_web
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html:ro
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - appnet

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: prediksi
      MYSQL_USER: prediksi
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - appnet

volumes:
  dbdata:

networks:
  appnet:
